CREATE DATABASE IF NOT EXISTS `crawlerv2` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'crawler'@'%' IDENTIFIED BY '841639647172n';
GRANT ALL PRIVILEGES ON `crawlerv2`.* TO 'crawler'@'%';
FLUSH PRIVILEGES;
